import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { isUUID } from 'class-validator';
import { Client, S3Error } from 'minio';
import type { Readable } from 'node:stream';
import type { ApiEnvironment } from '@api/config/environment';
import {
  ScanStorageError,
  type ScanStoragePort,
} from '../../application/ports/scan-storage.port';

/** Private S3-compatible scan storage backed by the official MinIO client. */
@Injectable()
export class MinioScanStorageAdapter implements ScanStoragePort, OnModuleInit {
  private readonly bucket: string;
  private readonly client: Client;
  private readonly logger = new Logger(MinioScanStorageAdapter.name);

  /**
   * Creates one immutable MinIO client from validated application configuration.
   *
   * @param config Validated API configuration.
   */
  constructor(config: ConfigService<ApiEnvironment, true>) {
    this.bucket = config.getOrThrow<string>('MINIO_BUCKET');
    this.client = new Client({
      accessKey: config.getOrThrow<string>('MINIO_ACCESS_KEY'),
      endPoint: config.getOrThrow<string>('MINIO_ENDPOINT'),
      port: config.getOrThrow<number>('MINIO_PORT'),
      secretKey: config.getOrThrow<string>('MINIO_SECRET_KEY'),
      useSSL: config.getOrThrow<boolean>('MINIO_USE_SSL'),
    });
  }

  /**
   * Ensures the configured private bucket exists before serving requests.
   *
   * @throws When MinIO cannot establish the application-owned bucket.
   */
  async onModuleInit(): Promise<void> {
    try {
      if (!(await this.client.bucketExists(this.bucket))) {
        try {
          await this.client.makeBucket(this.bucket);
        } catch (error) {
          if (!isOwnedBucketRace(error)) {
            throw error;
          }
        }
      }
      this.logger.log({ event: 'scan_storage_readiness', outcome: 'ready' });
    } catch {
      this.logger.error({
        event: 'scan_storage_readiness',
        outcome: 'failed',
      });
      throw new Error('Private scan storage initialization failed');
    }
  }

  /**
   * Verifies that the application-owned private bucket remains reachable.
   *
   * @throws ScanStorageError when MinIO is unavailable or the bucket is absent.
   */
  async checkReadiness(): Promise<void> {
    try {
      if (!(await this.client.bucketExists(this.bucket))) {
        throw new ScanStorageError('unavailable');
      }
    } catch (error) {
      throw translateStorageError(error);
    }
  }

  /**
   * Stores one bounded scan under a flat opaque key.
   *
   * @param storageKey Application-generated UUID key.
   * @param content Structurally validated PLY bytes.
   * @throws ScanStorageError when storage is unavailable.
   */
  async write(storageKey: string, content: Buffer): Promise<void> {
    try {
      await this.client.putObject(
        this.bucket,
        validateStorageKey(storageKey),
        content,
        content.length,
        { 'Content-Type': 'application/octet-stream' },
      );
    } catch (error) {
      throw translateStorageError(error);
    }
  }

  /**
   * Removes exactly one opaque object during metadata compensation.
   *
   * @param storageKey Application-generated UUID key.
   * @throws ScanStorageError when storage is unavailable.
   */
  async remove(storageKey: string): Promise<void> {
    try {
      await this.client.removeObject(
        this.bucket,
        validateStorageKey(storageKey),
      );
    } catch (error) {
      throw translateStorageError(error);
    }
  }

  /**
   * Opens one authorized object and verifies its size against persisted metadata.
   *
   * @param storageKey Opaque key loaded from owner-scoped metadata.
   * @param expectedSizeBytes Persisted exact object size.
   * @returns MinIO stream and verified content length.
   * @throws ScanStorageError when the object is absent, inconsistent, or unavailable.
   */
  async open(
    storageKey: string,
    expectedSizeBytes: number,
  ): Promise<{ sizeBytes: number; stream: Readable }> {
    try {
      const objectName = validateStorageKey(storageKey);
      const metadata = await this.client.statObject(this.bucket, objectName);
      if (metadata.size !== expectedSizeBytes) {
        throw new ScanStorageError('unavailable');
      }
      return {
        sizeBytes: metadata.size,
        stream: await this.client.getObject(this.bucket, objectName),
      };
    } catch (error) {
      throw translateStorageError(error);
    }
  }
}

/**
 * Restricts object access to the flat UUID namespace generated by the application.
 *
 * @param storageKey Key loaded from application or persistence state.
 * @returns Validated flat object name.
 * @throws ScanStorageError when the key could address another namespace.
 */
function validateStorageKey(storageKey: string): string {
  if (!isUUID(storageKey)) {
    throw new ScanStorageError('unavailable');
  }
  return storageKey;
}

/**
 * Recognizes the harmless race where another API instance created the bucket.
 *
 * @param error Unknown MinIO bucket-creation failure.
 * @returns Whether the configured bucket is already owned by these credentials.
 */
function isOwnedBucketRace(error: unknown): boolean {
  return error instanceof S3Error && error.code === 'BucketAlreadyOwnedByYou';
}

/**
 * Removes MinIO details from storage failures before they cross the port.
 *
 * @param error Unknown SDK or stream failure.
 * @returns Provider-neutral storage error.
 */
function translateStorageError(error: unknown): ScanStorageError {
  if (error instanceof ScanStorageError) {
    return error;
  }
  if (
    error instanceof S3Error &&
    (error.code === 'NoSuchKey' || error.code === 'NotFound')
  ) {
    return new ScanStorageError('not_found');
  }
  return new ScanStorageError('unavailable');
}
