/** Stable machine-readable error codes exposed by the current API slice. */
export const ProblemCode = {
  ACCOUNT_ALREADY_EXISTS: 'ACCOUNT_ALREADY_EXISTS',
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
  AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
  AUTH_RATE_LIMITED: 'AUTH_RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  PATIENT_NOT_FOUND: 'PATIENT_NOT_FOUND',
  PATIENT_PHOTO_INVALID_CONTENT: 'PATIENT_PHOTO_INVALID_CONTENT',
  PATIENT_PHOTO_STORAGE_UNAVAILABLE: 'PATIENT_PHOTO_STORAGE_UNAVAILABLE',
  PATIENT_PHOTO_TOO_LARGE: 'PATIENT_PHOTO_TOO_LARGE',
  PATIENT_PHOTO_UNSUPPORTED_TYPE: 'PATIENT_PHOTO_UNSUPPORTED_TYPE',
  PRINTING_CAPACITY_REACHED: 'PRINTING_CAPACITY_REACHED',
  PRINTING_UNAVAILABLE: 'PRINTING_UNAVAILABLE',
  PRINT_REQUEST_CONFLICT: 'PRINT_REQUEST_CONFLICT',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  SCAN_INVALID_CONTENT: 'SCAN_INVALID_CONTENT',
  SCAN_NOT_FOUND: 'SCAN_NOT_FOUND',
  SCAN_STORAGE_UNAVAILABLE: 'SCAN_STORAGE_UNAVAILABLE',
  SCAN_TOO_LARGE: 'SCAN_TOO_LARGE',
  SCAN_UNSUPPORTED_TYPE: 'SCAN_UNSUPPORTED_TYPE',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
} as const;

/** Union of stable problem codes derived from the canonical value map. */
export type ProblemCode = (typeof ProblemCode)[keyof typeof ProblemCode];
