import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { isUUID } from 'class-validator';
import { Client, S3Error } from 'minio';
import type { Readable } from 'node:stream';
import type { ApiEnvironment } from '@api/config/environment';
import {
  PrivateObjectStorageError,
  type PrivateObjectStoragePort,
} from './private-object-storage.port';

/** Private S3-compatible object storage backed by the official MinIO client. */
@Injectable()
export class MinioPrivateObjectStorageAdapter
  implements PrivateObjectStoragePort, OnModuleInit
{
  private readonly bucket: string;
  private readonly client: Client;
  private readonly logger = new Logger(MinioPrivateObjectStorageAdapter.name);

  /**
   * Creates one immutable MinIO client from validated configuration.
   *
   * @param config Validated API configuration.
   */
  constructor(config: ConfigService<ApiEnvironment, true>) {
    this.bucket = config.getOrThrow<string>('MINIO_BUCKET');
    this.client = new Client({
      accessKey: config.getOrThrow<string>('MINIO_ACCESS_KEY'),
      endPoint: config.getOrThrow<string>('MINIO_ENDPOINT'),
      port: config.getOrThrow<number>('MINIO_PORT'),
      secretKey: config.getOrThrow<string>('MINIO_SECRET_KEY'),
      useSSL: config.getOrThrow<boolean>('MINIO_USE_SSL'),
    });
  }

  /**
   * Ensures the configured private bucket exists before serving requests.
   *
   * @throws When MinIO cannot establish the application-owned bucket.
   */
  async onModuleInit(): Promise<void> {
    try {
      if (!(await this.client.bucketExists(this.bucket))) {
        try {
          await this.client.makeBucket(this.bucket);
        } catch (error) {
          if (!isOwnedBucketRace(error)) {
            throw error;
          }
        }
      }
      this.logger.log({ event: 'private_storage_readiness', outcome: 'ready' });
    } catch {
      this.logger.error({
        event: 'private_storage_readiness',
        outcome: 'failed',
      });
      throw new Error('Private object storage initialization failed');
    }
  }

  /**
   * Verifies that the private bucket remains reachable.
   *
   * @throws PrivateObjectStorageError when MinIO is unavailable or absent.
   */
  async checkReadiness(): Promise<void> {
    try {
      if (!(await this.client.bucketExists(this.bucket))) {
        throw new PrivateObjectStorageError('unavailable');
      }
    } catch (error) {
      throw translateStorageError(error);
    }
  }

  /**
   * Stores one bounded object under a flat opaque key.
   *
   * @param storageKey Application-generated UUID key.
   * @param content Validated bounded bytes.
   * @param contentType Validated media type.
   * @throws PrivateObjectStorageError when storage is unavailable.
   */
  async write(
    storageKey: string,
    content: Buffer,
    contentType: string,
  ): Promise<void> {
    try {
      await this.client.putObject(
        this.bucket,
        validateStorageKey(storageKey),
        content,
        content.length,
        { 'Content-Type': contentType },
      );
    } catch (error) {
      throw translateStorageError(error);
    }
  }

  /**
   * Removes exactly one opaque object during compensation or cleanup.
   *
   * @param storageKey Application-generated UUID key.
   * @throws PrivateObjectStorageError when storage is unavailable.
   */
  async remove(storageKey: string): Promise<void> {
    try {
      await this.client.removeObject(
        this.bucket,
        validateStorageKey(storageKey),
      );
    } catch (error) {
      throw translateStorageError(error);
    }
  }

  /**
   * Opens one authorized object and verifies persisted byte length.
   *
   * @param storageKey Opaque key loaded from owner-scoped metadata.
   * @param expectedSizeBytes Persisted exact byte length.
   * @returns MinIO stream and verified content length.
   * @throws PrivateObjectStorageError when absent, inconsistent, or unavailable.
   */
  async open(
    storageKey: string,
    expectedSizeBytes: number,
  ): Promise<{ sizeBytes: number; stream: Readable }> {
    try {
      const objectName = validateStorageKey(storageKey);
      const metadata = await this.client.statObject(this.bucket, objectName);
      if (metadata.size !== expectedSizeBytes) {
        throw new PrivateObjectStorageError('unavailable');
      }
      return {
        sizeBytes: metadata.size,
        stream: await this.client.getObject(this.bucket, objectName),
      };
    } catch (error) {
      throw translateStorageError(error);
    }
  }
}

/** Restricts object access to the flat UUID namespace generated by the API. */
function validateStorageKey(storageKey: string): string {
  if (!isUUID(storageKey)) {
    throw new PrivateObjectStorageError('unavailable');
  }
  return storageKey;
}

/** Recognizes concurrent creation of the configured application-owned bucket. */
function isOwnedBucketRace(error: unknown): boolean {
  return error instanceof S3Error && error.code === 'BucketAlreadyOwnedByYou';
}

/** Removes MinIO details from failures before they cross the storage port. */
function translateStorageError(error: unknown): PrivateObjectStorageError {
  if (error instanceof PrivateObjectStorageError) {
    return error;
  }
  if (
    error instanceof S3Error &&
    (error.code === 'NoSuchKey' || error.code === 'NotFound')
  ) {
    return new PrivateObjectStorageError('not_found');
  }
  return new PrivateObjectStorageError('unavailable');
}
